#!/bin/bash

set -Eeuo pipefail
trap 'code=$?; echo "❌ reset.sh failed at line ${BASH_LINENO[0]} (exit ${code})"; exit ${code}' ERR

ensure_encryption_key() {
    local env_file=".env"

    if [ ! -f "$env_file" ]; then
        return
    fi

    if [ -n "${ENCRYPTION_KEY:-}" ]; then
        return
    fi

    local current_key
    current_key=$(grep -E '^ENCRYPTION_KEY=' "$env_file" | tail -n 1 | cut -d '=' -f 2- || true)
    current_key=$(echo "${current_key}" | tr -d '"'\''[:space:]')

    if [ -n "$current_key" ]; then
        export ENCRYPTION_KEY="$current_key"
        return
    fi

    # 32 chars -> valid AES-256 key length expected by backend.
    # Avoid SIGPIPE issues under `set -o pipefail` by not using head on infinite streams.
    local generated_key
    generated_key=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || true)
    generated_key=${generated_key//-/}
    generated_key=${generated_key//[[:space:]]/}
    if [ -z "$generated_key" ] || [ "${#generated_key}" -ne 32 ]; then
        generated_key=$(openssl rand -hex 16 2>/dev/null || true)
    fi
    if [ -z "$generated_key" ] || [ "${#generated_key}" -ne 32 ]; then
        echo "❌ Failed to generate ENCRYPTION_KEY automatically."
        echo "Set ENCRYPTION_KEY in .env with 32 chars and rerun."
        exit 1
    fi
    echo "" >> "$env_file"
    echo "# Auto-generated by reset.sh for local encrypted fields" >> "$env_file"
    echo "ENCRYPTION_KEY=${generated_key}" >> "$env_file"
    export ENCRYPTION_KEY="$generated_key"
    echo "✅ ENCRYPTION_KEY was missing and has been generated in ${env_file}."
}

ensure_prod_basic_auth() {
    local htpasswd_file="ops/nginx/.htpasswd"
    local hosts_map_file="ops/nginx/.basic-auth-hosts.map"
    if [[ ! -f "${htpasswd_file}" ]]; then
        echo "❌ Missing ${htpasswd_file}."
        echo "Create it with:"
        echo "   ./scripts/set-basic-auth.sh <username> <password> <domain[,domain2,...]>"
        exit 1
    fi

    if ! grep -Eq '^[^:#[:space:]]+:[^[:space:]]+' "${htpasswd_file}"; then
        echo "❌ ${htpasswd_file} does not contain a valid htpasswd entry."
        echo "Recreate it with:"
        echo "   ./scripts/set-basic-auth.sh <username> <password> <domain[,domain2,...]>"
        exit 1
    fi

    if [[ ! -f "${hosts_map_file}" ]]; then
        echo "❌ Missing ${hosts_map_file}."
        echo "Create it with:"
        echo "   ./scripts/set-basic-auth.sh <username> <password> <domain[,domain2,...]>"
        exit 1
    fi

    if ! grep -Eq '^[[:space:]]*[^#[:space:]]+[[:space:]]+"Restricted Access";' "${hosts_map_file}"; then
        echo "❌ ${hosts_map_file} does not contain valid host entries."
        echo "Recreate it with:"
        echo "   ./scripts/set-basic-auth.sh <username> <password> <domain[,domain2,...]>"
        exit 1
    fi
}

has_cli_flag() {
    local needle="$1"
    shift || true
    for arg in "$@"; do
        if [[ "${arg}" == "${needle}" ]]; then
            return 0
        fi
    done
    return 1
}

is_prod_proxy_running() {
    docker ps --format '{{.Names}}' | grep -qx 'benchmarking-nginx-prod'
}

reload_prod_proxy_auth_if_needed() {
    if ! has_cli_flag "--soft-reset" "$@"; then
        return
    fi

    if ! is_prod_proxy_running; then
        return
    fi

    ensure_prod_basic_auth
    echo "🔐 --soft-reset detected and production proxy is running. Reloading auth-protected proxy..."
    docker compose --env-file .env.prod -f docker-compose.proxy.prod.yml up -d nginx
    docker compose --env-file .env.prod -f docker-compose.proxy.prod.yml restart nginx
}

ensure_encryption_key
echo "ℹ️ Running reset with args: $*"

# Always rebuild reset tool to avoid stale binary behavior after backend changes.
echo "🔧 Building reset tool..."
(cd server_go && go build -o ../reset ./cmd/reset)
echo "✅ Reset tool built."

# Check for --prod flag
if [[ "${1:-}" == "--prod" ]]; then
    ensure_prod_basic_auth
    echo "🚀 Updating Production (App & Proxy)..."
    (cd frontend && npm run build) && \
    docker compose --env-file .env.prod -f docker-compose.prod.yml up -d --build go-api-prod && \
    docker compose --env-file .env.prod -f docker-compose.proxy.prod.yml up -d && \
    docker compose --env-file .env.prod -f docker-compose.proxy.prod.yml restart nginx
    exit 0
fi

# Run reset with args
./reset "$@" && \
ensure_prod_basic_auth && \
docker compose -f docker-compose.proxy.yml down && \
docker compose -f docker-compose.proxy.yml up -d && \
reload_prod_proxy_auth_if_needed "$@"
