<template>
  <div class="docs-view">
    <div class="docs-header">
      <h1>📂 Documentation & Guides</h1>
      <p>Master your benchmarking environment and agent evaluations.</p>
    </div>

    <div class="docs-content">
      <!-- Section: Agents -->
      <section class="docs-section">
        <h2>🤖 Agent Configuration</h2>
        <div class="card">
          <h3>Corvic Agents (MCP)</h3>
          <p>These are agents connected via the <strong>Model Context Protocol</strong>. They leverage specialized tools and context to answer questions.</p>
          <ul>
            <li><strong>Endpoint URL:</strong> The HTTP/SSE endpoint where your agent listener is running.</li>
            <li><strong>Token:</strong> Security token for your agent. Use <code>MOCK</code> for dry-runs.</li>
            <li><strong>Max Parallel Requests:</strong> Limits how many concurrent questions this agent processes. Defaults to 5.</li>
          </ul>
        </div>
      </section>

      <!-- Section: Evaluators -->
      <section class="docs-section">
        <h2>⚖️ Evaluator Agents</h2>
        <p>Evaluators are specialized agents powered by the <strong>OpenAI API</strong>. They analyze responses from other agents, comparing them against expected answers (when provided) to calculate accuracy and quality scores.</p>
        
        <div class="card">
          <h3>1. OpenAI Setup</h3>
          <p>To use an Evaluator, you need to configure your API credentials:</p>
          <ul>
            <li>Go to the <a href="https://platform.openai.com/" target="_blank">OpenAI Platform</a>.</li>
            <li>In <strong>API Keys</strong>, create a new secret key.</li>
            <li>In <strong>Settings > Billing</strong>, ensure you have credits available.</li>
            <li>In <strong>Agent Manager</strong>, create an agent with provider <code>evaluator</code> (OpenAI) and paste your key in the <code>api_key</code> field.</li>
          </ul>
        </div>

        <div class="card highlight">
          <h3>2. Recommended System Prompt</h3>
          <p>Configure your <strong>Evaluator Agent</strong> with this system prompt to ensure consistent and strict benchmarking results:</p>
          
          <div class="code-block-container">
            <button class="btn-copy" @click="copyToClipboard">
              {{ copied ? '✅ Copied!' : '📋 Copy Prompt' }}
            </button>
            <div class="code-block" ref="codeBlock">
            <pre><code>You are a strict evaluator of responses generated by an LLM Agent for RAG benchmarking purposes.

Your task is to evaluate the quality, correctness, and relevance of a given response in relation to a user question and, when available, an expected answer.

Evaluation rules:

1. Input validation:
   - If the response payload is empty, null, or missing, you MUST state clearly that the response is empty and assign a score of 0/10.
   - If the user question is missing or empty, state that the evaluation cannot be performed and assign a score of 0/10.

2. Expected answer handling:
   - If an expected answer is provided, you MUST paste the expected answer verbatim at the very top of your response before any evaluation text.
   - In this case, evaluate the response strictly by comparing it to the expected answer, focusing on factual correctness, completeness, and alignment.
   - Hallucinations, missing key points, or contradictions MUST significantly reduce the score.

3. No expected answer scenario:
   - If no expected answer is provided, infer whether the response adequately addresses the user question.
   - Evaluate based on relevance, logical coherence, correctness, and usefulness.
   - If the response does not clearly answer the question or is mostly vague, misleading, or incorrect, assign a low score.

4. Scoring criteria:
   - 10/10 = Excellent: fully correct, complete, clear, and directly addresses the question.
   - 5/10 = Acceptable: partially correct or useful but with noticeable issues or omissions.
   - 0/10 = Unacceptable: empty, irrelevant, incorrect, incoherent, or misleading.

5. Output format:
   - Always provide a brief justification for the score.
   - Always end the response with a numeric score in the format: X/10.
   - The score MUST appear at the end of the response and nowhere else.

Be objective, consistent, and strict. Do not provide suggestions or rewritten answers. Only evaluate.</code></pre>
            </div>
          </div>
        </div>
      </section>

      <!-- Section: General Tips -->
      <section class="docs-section">
        <h2>💡 Tips & Best Practices</h2>
        <div class="tips-grid">
          <div class="tip-card">
            <h4>Rate Limiting</h4>
            <p>If you see <code>429 Too Many Requests</code>, reduce the "Max Parallel Requests" in Agent settings or check your API quotas.</p>
          </div>
          <div class="tip-card">
            <h4>Caching</h4>
            <p>The system caches results to improve performance. Use "Re-run" on a specific question if you want to bypass the cache and force a new execution.</p>
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const codeBlock = ref(null)
const copied = ref(false)

async function copyToClipboard() {
  const text = codeBlock.value.innerText
  try {
    await navigator.clipboard.writeText(text)
    copied.value = true
    setTimeout(() => {
      copied.value = false
    }, 2000)
  } catch (err) {
    console.error('Failed to copy text: ', err)
  }
}
</script>

<style scoped>
.docs-view {
  max-width: 1000px;
  margin: 0 auto;
  padding: 2rem;
}

.docs-header {
  margin-bottom: 3rem;
  text-align: center;
}

.docs-header h1 {
  font-size: 2.5rem;
  color: #1a1f36;
  margin-bottom: 0.5rem;
}

.docs-header p {
  font-size: 1.125rem;
  color: #64748b;
}

.docs-section {
  margin-bottom: 4rem;
}

.docs-section h2 {
  font-size: 1.75rem;
  color: #1a1f36;
  border-bottom: 2px solid #e2e8f0;
  padding-bottom: 0.5rem;
  margin-bottom: 1.5rem;
}

.card {
  background: white;
  border-radius: 12px;
  padding: 2rem;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
  margin-bottom: 1.5rem;
}

.card.highlight {
  border-left: 6px solid #6366f1;
}

.card h3 {
  margin-top: 0;
  margin-bottom: 1rem;
  color: #1a1f36;
}

.card p {
  color: #475569;
  line-height: 1.6;
}

.card ul {
  color: #475569;
  padding-left: 1.5rem;
}

.card li {
  margin-bottom: 0.5rem;
}

.code-block-container {
  position: relative;
  margin-top: 1.5rem;
}

.btn-copy {
  position: absolute;
  top: 0.5rem;
  right: 0.5rem;
  z-index: 10;
  padding: 0.5rem 1rem;
  font-size: 0.75rem;
  font-weight: 600;
  background: white;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s;
  box-shadow: 0 1px 2px rgba(0,0,0,0.05);
}

.btn-copy:hover {
  background: #f8fafc;
  border-color: #cbd5e1;
}

.code-block {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 1.5rem;
  padding-top: 3rem; /* Space for copy button */
  overflow-x: auto;
  max-height: 300px;
  overflow-y: auto;
}

.code-block::-webkit-scrollbar {
  width: 8px;
}

.code-block::-webkit-scrollbar-track {
  background: #f1f5f9;
  border-radius: 0 8px 8px 0;
}

.code-block::-webkit-scrollbar-thumb {
  background: #cbd5e1;
  border-radius: 4px;
}

.code-block::-webkit-scrollbar-thumb:hover {
  background: #94a3b8;
}

.code-block pre {
  margin: 0;
  font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', monospace;
  font-size: 0.875rem;
  line-height: 1.7;
  color: #1e293b;
  white-space: pre-wrap;
}

.docs-actions {
  display: flex;
  gap: 1rem;
  margin-top: 1.5rem;
}

.docs-actions .btn {
  text-decoration: none;
  font-size: 0.875rem;
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
}

.tips-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 1.5rem;
}

.tip-card {
  background: #fdf2f8;
  border: 1px solid #fbcfe8;
  border-radius: 12px;
  padding: 1.5rem;
}

.tip-card h4 {
  margin-top: 0;
  color: #9d174d;
  margin-bottom: 0.5rem;
}

.tip-card p {
  color: #be185d;
  font-size: 0.9375rem;
  margin: 0;
}
</style>
