<template>
  <div class="print-report">
    <!-- Cover Page -->
    <div class="print-page cover-page">
      <div class="header-decoration"></div>
      
      <div class="report-header">
        <div class="logo-wrapper">
          <CorvicLogo width="180px" height="50px" />
        </div>
        <h1>LLM Benchmark Analysis</h1>
        <div class="report-meta">
          <div class="meta-badge">
            <span class="meta-label">Workspace:</span>
            <span class="meta-value">{{ workspaceName }}</span>
          </div>
          <div class="meta-badge">
            <span class="meta-label">Generated:</span>
            <span class="meta-value">{{ reportDate }}</span>
          </div>
        </div>
      </div>

      <div class="summary-section-print" v-if="summaryStats && summaryStats.agents">
        <h2 class="section-title">Performance Executive Summary</h2>
        
        <div class="summary-grid-print">
          <div 
            v-for="(agent, idx) in summaryStats.agents" 
            :key="agent.name"
            class="agent-summary-card"
            :class="'card-accent-' + (idx % 4 + 1)"
          >
            <div class="card-header">
              <h3>{{ agent.name }}</h3>
              <div class="evaluator-badge" v-if="agent.provider === 'openai'">
                Evaluator
              </div>
              <div class="quality-circle" v-else>
                <span class="score">{{ agent.qualityScore }}%</span>
                <span class="label">Quality</span>
              </div>
            </div>
            
            <div class="stats-mini-list" v-if="agent.stats">
              <div class="mini-stat">
                <span class="val">{{ shouldShowStatus(agent) ? `${agent.stats.answered} / ${agent.stats.totalQuestions}` : agent.stats.answered }}</span>
                <span class="lab">Answered</span>
              </div>
              <div class="mini-stat">
                <span class="val">{{ formatDuration(agent.stats.avgDuration) }}</span>
                <span class="lab">Avg Speed</span>
              </div>
              <div class="mini-stat">
                <span class="val">{{ agent.provider === 'openai' ? agent.stats.answered : (agent.stats.percentages.positive || 0) + '%' }}</span>
                <span class="lab">{{ agent.provider === 'openai' ? 'Evaluations' : 'Precision' }}</span>
              </div>
            </div>

            <div class="validations-bar" v-if="agent.provider !== 'openai' && agent.stats && agent.stats.percentages">
              <div class="v-segment pos" :style="{ width: agent.stats.percentages.positive + '%' }"></div>
              <div class="v-segment alt" :style="{ width: agent.stats.percentages.alternative + '%' }"></div>
              <div class="v-segment par" :style="{ width: agent.stats.percentages.partial + '%' }"></div>
              <div class="v-segment neg" :style="{ width: agent.stats.percentages.negative + '%' }"></div>
            </div>

            <div class="evaluator-notice" v-if="agent.provider === 'openai'">
              This agent is only an evaluator of the quality of the responses generated by the evaluated agent.
            </div>
          </div>
        </div>

        <div class="findings-container" v-if="summaryStats.comparison">
          <h2 class="section-title">Benchmark Insight</h2>
          <div class="findings-grid">
            <div class="finding-box best-quality">
              <div class="finding-icon">🏆</div>
              <div class="finding-content">
                <span class="f-label">Quality Leader</span>
                <span class="f-value">{{ summaryStats.comparison.betterRatedAgent }}</span>
              </div>
            </div>
            <div class="finding-box fastest">
              <div class="finding-icon">⚡</div>
              <div class="finding-content">
                <span class="f-label">Speed Leader</span>
                <span class="f-value">{{ summaryStats.comparison.fasterAgent }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="footer-decoration">
        <p>This report was automatically generated by Corvic AI Comparison Suite.</p>
        <div class="dot-pattern"></div>
      </div>
    </div>

    <!-- Results Pages -->
    <div 
      v-for="(question, qIndex) in results" 
      :key="qIndex"
      class="print-page result-page"
    >
      <div class="page-header-mini">
        <span class="workspace-ref">{{ workspaceName }} Benchmark</span>
        <span class="page-num">Item #{{ qIndex + 1 }}</span>
      </div>

      <div class="question-container">
        <div class="q-badge">Question</div>
        <p class="q-text">{{ typeof question.question === 'object' ? question.question.question : question.question }}</p>
      </div>

      <div class="question-container expected-container" v-if="question.expectedAnswer">
        <div class="q-badge expected-badge">Expected Answer</div>
        <div class="q-text expected-text" v-html="renderMarkdown(question.expectedAnswer)"></div>
      </div>

      <div class="responses-comparison-grid">
        <div 
          v-for="(ans, aIndex) in question.agents" 
          :key="aIndex"
          class="response-card"
        >
          <div class="response-header">
            <div class="agent-info">
              <span class="agent-name">{{ ans.name }}</span>
              <span class="provider-pill">{{ ans.provider }}</span>
            </div>
            <div v-if="ans.humanValidation" class="validation-status" :class="ans.humanValidation">
              {{ getValidationIcon(ans.humanValidation) }}
              <span class="v-text">{{ ans.humanValidation }}</span>
            </div>
          </div>
          
          <div class="response-body">
            <div v-if="ans.error" class="error-box">
              <span class="error-icon">❌</span>
              <div class="error-content">
                <strong>Execution Error</strong>
                <p>{{ ans.error }}</p>
              </div>
            </div>
            <div 
              v-else-if="ans.answer" 
              class="markdown-content" 
              v-html="renderMarkdown(ans.answerText || ans.answer)"
            ></div>
            <div v-else class="empty-state">
              <em>Waiting for manual response input...</em>
            </div>
          </div>

          <div class="response-footer" v-if="ans.duration">
            <div class="meta-pill">
              <span class="icon">⏱️</span>
              {{ ans.duration }}s
            </div>
          </div>
        </div>
      </div>
      
      <div class="page-footer-mini">
        Confidential - Generated for {{ workspaceName }}
      </div>
    </div>
  </div>
</template>

<script>
import CorvicLogo from './CorvicLogo.vue'
import { processContent } from '../utils/markdown.js'

export default {
  name: 'PrintReport',
  components: {
    CorvicLogo
  },
  props: {
    workspaceName: String,
    summaryStats: Object,
    results: Array
  },
  computed: {
    reportDate() {
      return new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
    }
  },
  methods: {
    renderMarkdown(text) {
      if (!text) return ''
      return processContent(text).html || text
    },
    formatDuration(value) {
      const seconds = parseFloat(value)
      if (Number.isFinite(seconds)) {
        return seconds >= 60 ? `${(seconds / 60).toFixed(1)} min` : `${seconds.toFixed(1)} s`
      }
      return '0 s'
    },
    getValidationIcon(type) {
      const icons = {
        positive: '👍',
        negative: '👎',
        alternative: '🔄',
        partial: '⚠️'
      }
      return icons[type] || ''
    },
    shouldShowStatus(agent) {
      if (!agent.stats) return false
      const stats = agent.stats
      const isRunComplete = (stats.answered + stats.errors) === stats.totalQuestions
      
      if (!isRunComplete) return true
      if (stats.errors > 0) return true
      
      if (agent.provider !== 'openai') {
         if (stats.validations.notEvaluated > 0) return true
      }
      
      return false
    }
  }
}
</script>

<style scoped>
.print-report {
  --primary: #49399d;
  --primary-light: #667eea;
  --secondary: #764ba2;
  --success: #10b981;
  --danger: #ef4444;
  --warning: #f59e0b;
  --info: #3b82f6;
  --bg-page: #ffffff;
  --text-main: #1f2937;
  --text-muted: #6b7280;
  --border: #e5e7eb;
  
  color: var(--text-main);
  font-family: 'Outfit', 'Inter', system-ui, sans-serif;
  background: var(--bg-page);
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}

/* Page Setup */
.print-page {
  padding: 50px;
  position: relative;
  box-sizing: border-box;
  background: white;
  margin-bottom: 2rem; /* Spacing for screen view */
}

@media print {
  .print-page {
    page-break-after: always;
    display: block !important;
    min-height: auto !important;
    height: auto !important;
    margin-bottom: 0;
  }
  .print-page:last-child {
    page-break-after: auto;
  }
}

/* Cover Page Decorations */
.header-decoration {
  position: absolute;
  top: 0;
  right: 0;
  width: 300px;
  height: 300px;
  background: linear-gradient(135deg, var(--primary-light) 0%, var(--secondary) 100%);
  clip-path: polygon(0 0, 100% 0, 100% 100%);
  opacity: 0.1;
  z-index: 0;
}

.footer-decoration {
  margin-top: 3rem;
  width: 100%;
  max-width: 900px;
  border-top: 1px solid var(--border);
  padding-top: 20px;
  color: var(--text-muted);
  font-size: 0.85rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.dot-pattern {
  width: 100px;
  height: 40px;
  background-image: radial-gradient(var(--border) 1.5px, transparent 1.5px);
  background-size: 8px 8px;
  opacity: 0.5;
}

/* Cover Page Content */
.cover-page {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
}

.logo-wrapper {
  margin-bottom: 2rem;
  filter: drop-shadow(0 4px 6px rgba(0,0,0,0.1));
}

.report-header h1 {
  font-size: 3.5rem;
  font-weight: 800;
  margin: 0 0 1.5rem 0;
  background: linear-gradient(90deg, var(--primary), var(--secondary));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  letter-spacing: -0.02em;
}

.report-meta {
  display: flex;
  gap: 15px;
  margin-bottom: 3rem;
}

.meta-badge {
  background: #f3f4f6;
  padding: 8px 16px;
  border-radius: 999px;
  font-size: 0.95rem;
  border: 1px solid var(--border);
}

.meta-label {
  color: var(--text-muted);
  font-weight: 500;
  margin-right: 6px;
}

.meta-value {
  color: var(--primary);
  font-weight: 700;
}

/* Summary Section */
.summary-section-print {
  width: 100%;
  max-width: 900px;
  text-align: left;
}

.section-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--primary);
  margin: 2rem 0 1.5rem 0;
  display: flex;
  align-items: center;
  gap: 10px;
}
.section-title::after {
  content: '';
  flex: 1;
  height: 2px;
  background: linear-gradient(90deg, var(--border), transparent);
}

.summary-grid-print {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 25px;
  margin-bottom: 3rem;
}

.agent-summary-card {
  background: #ffffff;
  border: 1px solid var(--border);
  border-radius: 16px;
  padding: 24px;
  position: relative;
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.05);
}

.agent-summary-card h3 {
  font-size: 1.25rem;
  margin: 0 0 1.5rem 0;
  color: #111827;
}

.quality-circle {
  position: absolute;
  top: 20px;
  right: 24px;
  width: 60px;
  height: 60px;
  border-radius: 50%;
  background: #f0fdf4;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  border: 2px solid var(--success);
}

.evaluator-badge {
  position: absolute;
  top: 20px;
  right: 24px;
  padding: 4px 12px;
  border-radius: 999px;
  background: #fdf2f8;
  color: #db2777;
  border: 1px solid #f9a8d4;
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.evaluator-notice {
  margin-top: 15px;
  padding-top: 15px;
  border-top: 1px dashed var(--border);
  font-size: 0.75rem;
  color: var(--text-muted);
  font-style: italic;
  line-height: 1.4;
}

.quality-circle .score {
  font-weight: 800;
  font-size: 1rem;
  color: var(--success);
  line-height: 1;
}

.quality-circle .label {
  font-size: 0.65rem;
  text-transform: uppercase;
  color: var(--success);
  font-weight: 700;
}

.stats-mini-list {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
  margin-bottom: 20px;
}

.mini-stat {
  display: flex;
  flex-direction: column;
}

.mini-stat .val {
  font-weight: 700;
  font-size: 1.1rem;
  color: #111827;
}

.mini-stat .lab {
  font-size: 0.75rem;
  color: var(--text-muted);
}

.validations-bar {
  display: flex;
  height: 8px;
  border-radius: 999px;
  overflow: hidden;
  background: #f3f4f6;
}

.v-segment { height: 100%; }
.v-segment.pos { background: var(--success); }
.v-segment.alt { background: var(--info); }
.v-segment.par { background: var(--warning); }
.v-segment.neg { background: var(--danger); }

/* Findings */
.findings-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 20px;
}

.finding-box {
  background: #f9fafb;
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 20px;
  display: flex;
  align-items: center;
  gap: 15px;
}

.finding-icon {
  font-size: 1.5rem;
}

.finding-content {
  display: flex;
  flex-direction: column;
}

.f-label {
  font-size: 0.8rem;
  color: var(--text-muted);
  font-weight: 600;
  text-transform: uppercase;
}

.f-value {
  font-weight: 800;
  color: var(--primary);
  font-size: 1rem;
}

/* Result Pages */
.result-page {
  display: flex;
  flex-direction: column;
}

.page-header-mini {
  display: flex;
  justify-content: space-between;
  font-size: 0.8rem;
  color: var(--text-muted);
  text-transform: uppercase;
  font-weight: 700;
  letter-spacing: 0.05em;
  margin-bottom: 2rem;
  border-bottom: 1px solid var(--border);
  padding-bottom: 10px;
}

.question-container {
  margin-bottom: 2rem;
  background: #f8fafc;
  padding: 24px;
  border-left: 6px solid var(--primary);
  border-radius: 0 12px 12px 0;
}

.q-badge {
  font-size: 0.7rem;
  background: var(--primary);
  color: white;
  padding: 3px 8px;
  border-radius: 4px;
  display: inline-block;
  margin-bottom: 8px;
  text-transform: uppercase;
  font-weight: 800;
}

.q-text {
  font-size: 1.4rem;
  font-weight: 700;
  color: #0f172a;
  margin: 0;
  line-height: 1.4;
}

.expected-container {
  background: #f0fdf4;
  border-left-color: #10b981;
  margin-top: -1rem;
  margin-bottom: 2rem;
  padding: 16px 24px;
}

.expected-badge {
  background: #10b981;
}

.expected-text {
  font-size: 1.1rem;
  font-weight: 500;
  color: #166534;
}

.responses-comparison-grid {
  display: flex;
  gap: 20px;
  align-items: stretch;
}

.response-card {
  flex: 1;
  min-width: 0;
  border: 1px solid var(--border);
  border-radius: 16px;
  display: flex;
  flex-direction: column;
  background: #ffffff;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
  page-break-inside: auto; 
  break-inside: auto;
}

.response-header {
  padding: 16px 20px;
  background: #fdfdfd;
  border-bottom: 1px solid var(--border);
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.agent-name {
  font-weight: 800;
  font-size: 1.1rem;
  color: #111827;
  margin-right: 10px;
}

.provider-pill {
  font-size: 0.7rem;
  color: var(--primary);
  background: #eff6ff;
  padding: 2px 8px;
  border-radius: 4px;
  font-weight: 700;
  text-transform: uppercase;
}

.validation-status {
  display: flex;
  align-items: center;
  gap: 5px;
  font-weight: 700;
  font-size: 0.85rem;
  padding: 4px 10px;
  border-radius: 6px;
}

.validation-status.positive { background: #dcfce7; color: #166534; }
.validation-status.negative { background: #fee2e2; color: #991b1b; }
.validation-status.alternative { background: #e0f2fe; color: #075985; }
.validation-status.partial { background: #fef3c7; color: #92400e; }

.response-body {
  padding: 20px;
  font-size: 1rem;
  line-height: 1.6;
  color: #374151;
}

.markdown-content :deep(pre) {
  background: #1e293b;
  color: #f8fafc;
  padding: 16px;
  border-radius: 8px;
  font-size: 0.9rem;
  margin: 1rem 0;
  overflow-x: auto;
  white-space: pre-wrap;
  word-break: break-all;
}

.markdown-content :deep(code) {
  font-family: 'Fira Code', 'Courier New', monospace;
}

.markdown-content :deep(img) {
  max-width: 100%;
  border-radius: 8px;
}

.markdown-content :deep(ul), 
.markdown-content :deep(ol) {
  padding-left: 1.5rem;
  margin: 1rem 0;
}

.markdown-content :deep(li) {
  margin-bottom: 0.5rem;
}

.response-footer {
  padding: 12px 20px;
  background: #f9fafb;
  border-top: 1px solid var(--border);
}

.meta-pill {
  font-size: 0.8rem;
  color: var(--text-muted);
  display: inline-flex;
  align-items: center;
  gap: 5px;
  background: white;
  padding: 4px 10px;
  border-radius: 999px;
  border: 1px solid var(--border);
}

.error-box {
  background: #fef2f2;
  border: 1px solid #fecaca;
  border-radius: 8px;
  padding: 16px;
  display: flex;
  gap: 12px;
}

.error-content strong {
  display: block;
  color: #991b1b;
  margin-bottom: 4px;
}

.error-content p {
  margin: 0;
  color: #dc2626;
  font-size: 0.9rem;
}

.page-footer-mini {
  margin-top: 20px;
  padding-top: 20px;
  font-size: 0.75rem;
  color: var(--text-muted);
  text-align: center;
}

/* Card Accents */
.card-accent-1 { border-top: 5px solid var(--primary); }
.card-accent-2 { border-top: 5px solid var(--secondary); }
.card-accent-3 { border-top: 5px solid var(--info); }
.card-accent-4 { border-top: 5px solid var(--success); }
</style>
