#!/usr/bin/env bash

set -Eeuo pipefail

if ! command -v openssl >/dev/null 2>&1; then
  echo "❌ openssl is required to generate htpasswd entries."
  exit 1
fi

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 <username> <password> <domain[,domain2,...]>"
  exit 1
fi

username="$1"
password="$2"
domains_csv="$3"

if [[ -z "${username}" || -z "${password}" || -z "${domains_csv}" ]]; then
  echo "❌ Username, password and domains cannot be empty."
  exit 1
fi

target_dir="ops/nginx"
htpasswd_file="${target_dir}/.htpasswd"
hosts_map_file="${target_dir}/.basic-auth-hosts.map"

mkdir -p "${target_dir}"

password_hash="$(openssl passwd -apr1 "${password}")"
printf "%s:%s\n" "${username}" "${password_hash}" > "${htpasswd_file}"
chmod 644 "${htpasswd_file}"

IFS=',' read -r -a raw_domains <<< "${domains_csv}"
domains=()
declare -A seen_domains=()
for domain in "${raw_domains[@]}"; do
  normalized="${domain,,}"
  normalized="${normalized#"${normalized%%[![:space:]]*}"}"
  normalized="${normalized%"${normalized##*[![:space:]]}"}"
  if [[ -z "${normalized}" ]]; then
    continue
  fi

  if [[ ! "${normalized}" =~ ^[a-z0-9.-]+$ ]] || [[ "${normalized}" == .* ]] || [[ "${normalized}" == *..* ]]; then
    echo "❌ Invalid domain: ${domain}"
    exit 1
  fi

  if [[ -z "${seen_domains[${normalized}]+x}" ]]; then
    seen_domains["${normalized}"]=1
    domains+=("${normalized}")
  fi
done

if [[ ${#domains[@]} -eq 0 ]]; then
  echo "❌ Provide at least one valid domain."
  exit 1
fi

{
  echo "# Generated by scripts/set-basic-auth.sh"
  echo "# One host per line for the nginx map used by ops/nginx/nginx.conf and ops/nginx/nginx.prod.conf"
  for domain in "${domains[@]}"; do
    printf '%s "Restricted Access";\n' "${domain}"
  done
} > "${hosts_map_file}"
chmod 644 "${hosts_map_file}"

echo "✅ Basic auth credentials written to ${htpasswd_file}"
echo "✅ Host map written to ${hosts_map_file}"
echo "ℹ️  Protected hosts: ${domains[*]}"
echo "ℹ️  Deploy with: ./reset.sh --prod"
