steps:
  - name: gcr.io/cloud-builders/docker
    script: |
      for service in agenteval-api agenteval-runner agenteval-web; do
        docker build -t ${_IMAGE_REPO_BASE}/${service}:${COMMIT_SHA} -t ${_IMAGE_REPO_BASE}/${service}:latest --file=infra/${service}/Dockerfile .
        docker push ${_IMAGE_REPO_BASE}/${service}:${COMMIT_SHA}
        docker push ${_IMAGE_REPO_BASE}/${service}:latest
      done

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    script: |
      #!/usr/bin/env bash
      set -eu -o pipefail

      for service in agenteval-api agenteval-runner agenteval-web; do
        gcloud run deploy ${service}-dev --image ${_IMAGE_REPO_BASE}/${service}:${COMMIT_SHA} --region ${_DEPLOY_REGION}
      done
    timeout: 480s
options:
  automapSubstitutions: true
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
