steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    script: bash infra/releng/tag-release-images-gcp.sh $(cat infra/releng/release-tag.txt) agenteval-api agenteval-web
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    script: |
      #!/usr/bin/env bash
      TOKEN=$(gcloud auth print-identity-token --audiences ${_TOKEN_AUDIENCE})
      curl --fail-with-body --no-progress-meter -XPOST -H "Authorization: Bearer $TOKEN" $_TOKEN_AUDIENCE/update/${COMMIT_SHA}
    env: [_TOKEN_AUDIENCE=https://update-agenteval-app-dev-main-n6lncvk3ma-uc.a.run.app]
options:
  automapSubstitutions: true
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
